plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = mod_version

repositories {
    maven {
        name = "Nucleoid"
        url = uri("https://maven.nucleoid.xyz")
    }
    maven {
        url = "https://jitpack.io"
        content {includeGroup "com.github.renardelectric"}
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "polyquest" {
            sourceSet sourceSets.main
        }
    }

    if (System.getProperty("idea.active") == "true") {
        runs {
            client {
                getProgramArguments().addAll(["--username", "RenardElectric", "--uuid", "81c5680f-418c-4389-8d5e-e319eb861ed6"])
            }
            configureEach {
                jvmArguments.add("-XX:+AllowEnhancedClassRedefinition")
                preferGradleTask.set(true)
            }
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation include("eu.pb4:common-economy-api:${common_economy_api_version}")
    implementation include("eu.pb4:sgui:${sgui_version}")
    implementation include("com.github.renardelectric:polycore:${polycore_version}")

    testImplementation platform("org.junit:junit-bom:6.1.3")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
    useJUnitPlatform()
    inputs.dir(layout.projectDirectory.dir("schemas"))
}

processResources {
    def resourceProperties = [
            mod_id: mod_id,
            mod_name: mod_name,
            mod_version: mod_version,
            minecraft_version: minecraft_version,
            loader_version: loader_version,
            java_version: java_version,
            fabric_api_version: fabric_api_version
    ]
    inputs.properties(resourceProperties)
    filesMatching("fabric.mod.json") {
        expand(resourceProperties)
    }
}

def targetJavaVersion = java_version as int
tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = targetJavaVersion
    options.compilerArgs.add("-Xlint:all,-classfile")
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    def licenseFileName = "LICENSE_${mod_id}.txt"
    from("LICENSE.txt") {
        rename("LICENSE.txt", licenseFileName)
    }
}
