package polycube.polyquest.signal;

import net.minecraft.advancements.AdvancementHolder;
import net.minecraft.advancements.predicates.BlockPredicate;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.state.BlockState;
import org.jspecify.annotations.Nullable;

import java.util.List;
import java.util.Set;

/// Normalized server-thread events consumed by condition instances.
public sealed interface QuestSignal
        permits QuestSignal.LootGenerated,
        QuestSignal.Advancement, QuestSignal.CriteriaMatched,
        QuestSignal.Explicit {
    ServerPlayer player();

    long serverTick();

    enum LootOrigin {
        ENTITY,
        FISHING,
        BLOCK
    }

    /// Retains the pre-break block context, since the world position may already contain air.
    record BlockLootSource(ServerLevel level, BlockState state, @Nullable BlockEntity blockEntity) {
        public boolean matches(BlockPredicate predicate) {
            return predicate.matchesState(state) && predicate.matchesBlockEntity(level, blockEntity);
        }
    }

    /// Finalized item stacks generated by one supported loot source for a player.
    record LootGenerated(
            ServerPlayer player,
            long serverTick,
            LootOrigin origin,
            @Nullable Entity sourceEntity,
            @Nullable BlockLootSource sourceBlock,
            List<ItemStack> items
    ) implements QuestSignal {
        public LootGenerated {
            items = items.stream().map(ItemStack::copy).toList();
        }
    }

    record Advancement(ServerPlayer player, long serverTick, AdvancementHolder advancement) implements QuestSignal {}

    /// All fake advancement criteria matched by one trigger evaluation.
    record CriteriaMatched(
            ServerPlayer player,
            long serverTick,
            Set<Identifier> registrationIds
    ) implements QuestSignal {
        public CriteriaMatched {
            registrationIds = Set.copyOf(registrationIds);
        }
    }

    record Explicit(ServerPlayer player, long serverTick, Identifier signalId) implements QuestSignal {}
}
